### 環境変数
@baseUrl = https://onpaku-api-157884168241.asia-northeast1.run.app/api/v1/onpaku
@apiKey = {{$dotenv API_KEY}}

### メールアドレスに紐づくPending状態のVC一覧を取得
GET {{baseUrl}}/vcs/pending?email=test@example.com
Authorization: Bearer {{apiKey}}

### VCをアクティベート
PATCH {{baseUrl}}/vcs/user_test@example.com/activate
Authorization: Bearer {{apiKey}}

### VCを無効化
PATCH {{baseUrl}}/vcs/user_test@example.com/revoke
Authorization: Bearer {{apiKey}} 