### 環境変数
@baseUrl = http://localhost:3000/api/v1/onpaku
@apiKey = MY_SECRET_KEY_1234

### ユーザー新規登録
POST {{baseUrl}}/user
Authorization: Bearer {{apiKey}}
Content-Type: application/json

{
  "id": "user123",
  "email": "test@example.com",
  "family_name": "山田",
  "first_name": "太郎",
  "birth_year": 1990,
  "gender": "male",
  "zip": "123-4567",
  "prefecture": "東京都",
  "address": "渋谷区",
  "street": "1-2-3",
  "tel": "03-1234-5678",
  "management_programs": []
}

### ユーザー更新
PATCH {{baseUrl}}/user
Authorization: Bearer {{apiKey}}
Content-Type: application/json

{
  "id": "user123",
  "email": "test@example.com",
  "family_name": "山田",
  "first_name": "次郎",
  "management_programs": [
    {
      "programId": "program123",
      "role": "partner"
    }
  ]
} 